/** Vietnamese labels shown to non-technical editors instead of API field names. */
export const CONTENT_MANAGER_FIELD_LABELS_VI: Readonly<Record<string, string>> = {
  address: 'Địa chỉ',
  adultPrice: 'Giá người lớn (VNĐ)',
  aLaCarte: 'Phần món gọi riêng',
  alt: 'Mô tả ảnh cho người dùng khiếm thị',
  amenities: 'Danh sách tiện ích',
  amenitiesHeading: 'Tiêu đề phần tiện ích',
  answer: 'Câu trả lời',
  area: 'Khu vực của ảnh',
  arrivalTimes: 'Các khung giờ khách có thể chọn',
  backgroundImage: 'Ảnh nền',
  body: 'Nội dung',
  bookingCta: 'Khối kêu gọi đặt bàn',
  bookingNotice: 'Lưu ý dưới biểu mẫu đặt bàn',
  bookingStrip: 'Khối đặt bàn cuối trang',
  brandName: 'Tên thương hiệu',
  buffet: 'Phần giới thiệu buffet',
  canonicalPath: 'Đường dẫn chuẩn SEO',
  caption: 'Chú thích ảnh',
  category: 'Nhóm món',
  childPrice: 'Giá trẻ em (VNĐ)',
  closesAt: 'Giờ kết thúc',
  closingCta: 'Khối kêu gọi cuối trang',
  coverImage: 'Ảnh bìa',
  craftBody: 'Nội dung kỹ nghệ chế biến',
  craftHeading: 'Tiêu đề kỹ nghệ chế biến',
  craftImage: 'Ảnh kỹ nghệ chế biến',
  decorativeImage: 'Ảnh trang trí',
  defaultSeo: 'SEO mặc định toàn website',
  description: 'Mô tả',
  displayOrder: 'Thứ tự hiển thị',
  drinks: 'Phần đồ uống',
  email: 'Email',
  eyebrow: 'Nhãn nhỏ phía trên tiêu đề',
  endsAt: 'Thời gian kết thúc',
  eventBody: 'Nội dung phần video / sự kiện',
  eventCta: 'Khối sự kiện riêng',
  eventHeading: 'Tiêu đề phần video / sự kiện',
  eventImage: 'Ảnh đại diện video / sự kiện',
  eventLink: 'Liên kết xem thêm',
  experience: 'Phần giới thiệu trải nghiệm',
  experienceBody: 'Nội dung trải nghiệm không gian',
  experienceHeading: 'Tiêu đề trải nghiệm không gian',
  experienceImage: 'Ảnh trải nghiệm không gian',
  faqHeading: 'Tiêu đề câu hỏi thường gặp',
  faqItems: 'Câu hỏi thường gặp',
  featuredCampaign: 'Chương trình nổi bật',
  featuredHeading: 'Nhãn phần nổi bật',
  featuredLocation: 'Chi nhánh hiển thị trên trang',
  featuredMenuItems: 'Các món nổi bật trên trang chủ',
  featuredPackage: 'Gói buffet hiển thị',
  features: 'Các điểm nổi bật',
  flavorItems: 'Các món thịt giới thiệu',
  flavorsHeading: 'Tiêu đề phần món thịt',
  focalPointX: 'Điểm lấy nét ngang (%)',
  focalPointY: 'Điểm lấy nét dọc (%)',
  footerExploreLinks: 'Liên kết cột “Khám phá”',
  footerInfoLinks: 'Liên kết cột “Thông tin”',
  formHeading: 'Tiêu đề biểu mẫu',
  formTopics: 'Các chủ đề liên hệ khách có thể chọn',
  fullName: 'Họ và tên khách',
  gallery: 'Bộ ảnh',
  galleryHeading: 'Tiêu đề bộ ảnh',
  galleryItems: 'Các ảnh hiển thị',
  guestCount: 'Số lượng khách',
  guestOptions: 'Các mức số lượng khách có thể chọn',
  headerLinks: 'Các mục trên thanh điều hướng',
  heading: 'Tiêu đề',
  helpBody: 'Đoạn giới thiệu phần hỗ trợ',
  helpHeading: 'Tiêu đề phần hỗ trợ',
  helpImage: 'Ảnh phần hỗ trợ',
  helpItems: 'Các nội dung hỗ trợ',
  hero: 'Khối mở đầu trang (Hero)',
  heroImage: 'Ảnh đại diện chi nhánh',
  hotline: 'Số hotline',
  image: 'Ảnh',
  images: 'Danh sách ảnh',
  includedItems: 'Nội dung có trong gói',
  ingredients: 'Các nguyên liệu nổi bật',
  ingredientsHeading: 'Tiêu đề phần nguyên liệu',
  introBody: 'Nội dung giới thiệu',
  introHeading: 'Tiêu đề giới thiệu',
  introImage: 'Ảnh giới thiệu',
  isActive: 'Đang hiển thị',
  isFeatured: 'Đánh dấu nổi bật',
  itemSectionHeading: 'Tiêu đề danh sách món',
  items: 'Các món thuộc nhóm',
  kind: 'Loại chương trình',
  label: 'Nhãn hiển thị',
  link: 'Nút / liên kết',
  listingHeading: 'Tiêu đề danh sách chương trình',
  location: 'Chi nhánh',
  logo: 'Logo thương hiệu',
  mainLocation: 'Chi nhánh chính',
  manifestoHeading: 'Thông điệp nổi bật',
  mapHeading: 'Tiêu đề bản đồ',
  mapUrl: 'Đường dẫn Google Maps',
  media: 'File ảnh',
  message: 'Nội dung khách gửi',
  menuHighlights: 'Phần món nổi bật',
  menuItems: 'Các món khách chọn',
  menuPackages: 'Các gói khách chọn',
  menuSelectionMode: 'Cách chọn thực đơn',
  metaDescription: 'Mô tả SEO',
  metaTitle: 'Tiêu đề SEO',
  name: 'Tên',
  noIndex: 'Ẩn khỏi công cụ tìm kiếm',
  note: 'Yêu cầu thêm của khách',
  notes: 'Các lưu ý đặt bàn',
  notesHeading: 'Tiêu đề phần lưu ý',
  number: 'Số thứ tự bước',
  occasion: 'Dịp đặc biệt',
  occasionBody: 'Mô tả phần dịp đặc biệt',
  occasionHeading: 'Tiêu đề phần dịp đặc biệt',
  occasionImage: 'Ảnh cạnh biểu mẫu đặt bàn',
  occasionOptions: 'Các dịp khách có thể chọn trong biểu mẫu',
  occasions: 'Các dịp được giới thiệu',
  openInNewTab: 'Mở liên kết trong tab mới',
  openingHours: 'Giờ mở cửa',
  opensAt: 'Giờ bắt đầu',
  operatingHours: 'Giờ hoạt động',
  originBody: 'Nội dung nguồn gốc thương hiệu',
  originHeading: 'Tiêu đề nguồn gốc thương hiệu',
  originImage: 'Ảnh nguồn gốc thương hiệu',
  overlapCount: 'Số yêu cầu trùng giờ',
  packageListingHeading: 'Tiêu đề phần các gói khác',
  packageSectionHeading: 'Tiêu đề phần gói buffet',
  phone: 'Số điện thoại',
  philosophyBody: 'Nội dung triết lý',
  philosophyHeading: 'Tiêu đề triết lý',
  philosophyImage: 'Ảnh phần triết lý',
  platform: 'Nền tảng mạng xã hội',
  portion: 'Khẩu phần / quy cách',
  preferredDate: 'Ngày khách muốn đến',
  preferredTime: 'Giờ khách muốn đến',
  price: 'Giá (VNĐ)',
  priceUnit: 'Đơn vị giá hiển thị',
  primaryLink: 'Nút chính',
  process: 'Phần quy trình phục vụ',
  processHeading: 'Tiêu đề quy trình',
  processSteps: 'Các bước trải nghiệm',
  question: 'Câu hỏi',
  ritualBody: 'Nội dung nghi thức Rodizio',
  ritualHeading: 'Tiêu đề nghi thức Rodizio',
  ritualImage: 'Ảnh nghi thức Rodizio',
  ritualLink: 'Nút trong phần Rodizio',
  rodizioPackage: 'Gói Rodizio hiển thị',
  scrollHint: 'Nhãn cuộn xuống',
  secondaryLink: 'Nút phụ',
  seo: 'Thông tin SEO',
  shareImage: 'Ảnh chia sẻ mạng xã hội',
  shortDescription: 'Mô tả ngắn trên thẻ món',
  slug: 'Đường dẫn ngắn (slug)',
  socialHeading: 'Tiêu đề phần mạng xã hội',
  socialLinks: 'Các kênh mạng xã hội',
  sourceLocale: 'Ngôn ngữ trang gửi',
  sourcePath: 'Trang đã gửi yêu cầu',
  space: 'Phần giới thiệu không gian',
  startsAt: 'Thời gian bắt đầu',
  status: 'Trạng thái xử lý',
  steps: 'Các bước',
  stepsHeading: 'Tiêu đề phần các bước',
  story: 'Phần câu chuyện thương hiệu',
  summary: 'Tóm tắt',
  supportBody: 'Nội dung hỗ trợ đặt bàn',
  supportHeading: 'Tiêu đề hỗ trợ đặt bàn',
  supportImage: 'Ảnh phần hỗ trợ đặt bàn',
  tableBody: 'Nội dung trải nghiệm tại bàn',
  tableHeading: 'Tiêu đề trải nghiệm tại bàn',
  tableImage: 'Ảnh trải nghiệm tại bàn',
  tagline: 'Slogan',
  terms: 'Điều kiện áp dụng',
  timelineEntries: 'Các mốc câu chuyện',
  timelineHeading: 'Tiêu đề dòng thời gian',
  title: 'Tiêu đề',
  topic: 'Chủ đề liên hệ',
  url: 'Đường dẫn',
  value: 'Giá trị hệ thống',
  values: 'Các giá trị thương hiệu',
  valuesHeading: 'Tiêu đề giá trị thương hiệu',
  video: 'Video',
  visitHeading: 'Tiêu đề phần thông tin ghé thăm',
  visitImage: 'Ảnh mặt tiền / không gian đón khách',
  zones: 'Các khu vực chỗ ngồi',
};

export const CONTENT_MANAGER_FIELD_DESCRIPTIONS_VI: Readonly<Record<string, string>> = {
  displayOrder: 'Số nhỏ hiển thị trước.',
  slug: 'Phần cuối của URL. Chỉ đổi khi hiểu ảnh hưởng đến liên kết cũ.',
  value: 'Mã ổn định dùng khi lưu dữ liệu. Không đổi nếu đã có dữ liệu thật.',
  arrivalTimes: 'Nhãn có thể dịch; giá trị giờ phải giữ ổn định, ví dụ 19:00.',
  guestOptions: 'Giá trị phải là số khách, ví dụ 2, 4 hoặc 6.',
};
