import { ReservationInboxTranslationKey } from './reservation-inbox.types';

export const reservationInboxVietnameseTranslations: Record<
  ReservationInboxTranslationKey,
  string
> = {
  [ReservationInboxTranslationKey.Title]: 'Hộp thư đặt bàn',
  [ReservationInboxTranslationKey.StatusStream]: 'Kết nối trực tiếp',
  [ReservationInboxTranslationKey.StatusPolling]: 'Đang kiểm tra mỗi 20 giây',
  [ReservationInboxTranslationKey.PrefOsNotify]: 'Thông báo hệ điều hành',
  [ReservationInboxTranslationKey.PrefSound]: 'Âm thanh',
  [ReservationInboxTranslationKey.OsNotifyDenied]:
    'Trình duyệt không cho phép thông báo. Hãy bật thông báo cho trang này rồi thử lại.',
  [ReservationInboxTranslationKey.ColumnCustomer]: 'Khách hàng',
  [ReservationInboxTranslationKey.ColumnPhone]: 'SĐT',
  [ReservationInboxTranslationKey.ColumnGuests]: 'Số khách',
  [ReservationInboxTranslationKey.ColumnDateTime]: 'Ngày giờ',
  [ReservationInboxTranslationKey.ColumnOverlap]: 'Trùng khung giờ',
  [ReservationInboxTranslationKey.ColumnReceivedAt]: 'Nhận lúc',
  [ReservationInboxTranslationKey.ColumnActions]: 'Thao tác',
  [ReservationInboxTranslationKey.ActionOpen]: 'Mở',
  [ReservationInboxTranslationKey.ActionMarkRead]: 'Đã đọc',
  [ReservationInboxTranslationKey.Empty]: 'Không có yêu cầu mới',
  [ReservationInboxTranslationKey.PillUnread]: 'đặt bàn mới',
  [ReservationInboxTranslationKey.PillAria]: '{count} đặt bàn mới',
  [ReservationInboxTranslationKey.OverlapCount]: 'Trùng {count}',
  [ReservationInboxTranslationKey.ToggleOn]: 'Bật',
  [ReservationInboxTranslationKey.ToggleOff]: 'Tắt',
  [ReservationInboxTranslationKey.ChipNew]: 'Mới',
  [ReservationInboxTranslationKey.ChipRead]: 'Đã đọc',
  [ReservationInboxTranslationKey.ChipArchived]: 'Lưu trữ',
  [ReservationInboxTranslationKey.FilterStatusLabel]: 'Trạng thái',
  [ReservationInboxTranslationKey.FilterAll]: 'Tất cả ({count})',
  [ReservationInboxTranslationKey.StatusNew]: 'Mới ({count})',
  [ReservationInboxTranslationKey.StatusRead]: 'Đã đọc ({count})',
  [ReservationInboxTranslationKey.StatusArchived]: 'Lưu trữ ({count})',
  [ReservationInboxTranslationKey.SearchLabel]: 'Tìm kiếm',
  [ReservationInboxTranslationKey.SearchPlaceholder]: 'Tìm theo tên hoặc số điện thoại',
  [ReservationInboxTranslationKey.SearchClear]: 'Xóa tìm kiếm',
  [ReservationInboxTranslationKey.ColumnStatus]: 'Trạng thái',
  [ReservationInboxTranslationKey.ActionArchive]: 'Lưu trữ',
  [ReservationInboxTranslationKey.ActionRestore]: 'Khôi phục',
  [ReservationInboxTranslationKey.ActionMarkNew]: 'Đánh dấu mới',
  [ReservationInboxTranslationKey.PaginationSummary]:
    'Trang {page}/{pageCount} · {total} yêu cầu',
  [ReservationInboxTranslationKey.PaginationPrev]: 'Trang trước',
  [ReservationInboxTranslationKey.PaginationNext]: 'Trang sau',
  [ReservationInboxTranslationKey.EmptyFiltered]: 'Không có yêu cầu nào khớp bộ lọc',
  [ReservationInboxTranslationKey.LoadFailed]: 'Không tải được danh sách. Vui lòng thử lại.',
  [ReservationInboxTranslationKey.ActionFailed]: 'Không cập nhật được trạng thái. Vui lòng thử lại.',
};
