import { AuditLogTranslationKey } from './audit-log.types';

export const auditLogVietnameseTranslations: Record<AuditLogTranslationKey, string> = {
  [AuditLogTranslationKey.Title]: 'Nhật ký hoạt động',
  [AuditLogTranslationKey.Export]: 'Xuất CSV',
  [AuditLogTranslationKey.Search]: 'Tìm kiếm',
  [AuditLogTranslationKey.SearchPlaceholder]: 'Tên, đối tượng hoặc mã',
  [AuditLogTranslationKey.Category]: 'Nhóm',
  [AuditLogTranslationKey.Action]: 'Hành động',
  [AuditLogTranslationKey.Source]: 'Nguồn',
  [AuditLogTranslationKey.Result]: 'Kết quả',
  [AuditLogTranslationKey.From]: 'Từ ngày',
  [AuditLogTranslationKey.To]: 'Đến ngày',
  [AuditLogTranslationKey.CategoryContent]: 'Nội dung',
  [AuditLogTranslationKey.CategoryAccount]: 'Tài khoản',
  [AuditLogTranslationKey.CategorySecurity]: 'Bảo mật',
  [AuditLogTranslationKey.CategoryError]: 'Lỗi',
  [AuditLogTranslationKey.ResultSuccess]: 'Thành công',
  [AuditLogTranslationKey.ResultFailure]: 'Thất bại',
  [AuditLogTranslationKey.ColumnTime]: 'Thời gian',
  [AuditLogTranslationKey.ColumnActor]: 'Người thực hiện',
  [AuditLogTranslationKey.ColumnAction]: 'Hoạt động',
  [AuditLogTranslationKey.ColumnSource]: 'Nguồn',
  [AuditLogTranslationKey.ColumnTarget]: 'Đối tượng',
  [AuditLogTranslationKey.ColumnResult]: 'Kết quả',
  [AuditLogTranslationKey.Empty]: 'Không có hoạt động nào trong khoảng thời gian này.',
  [AuditLogTranslationKey.Loading]: 'Đang tải nhật ký…',
  [AuditLogTranslationKey.Error]: 'Không thể tải nhật ký lúc này. Vui lòng thử lại.',
  [AuditLogTranslationKey.Retry]: 'Thử lại',
  [AuditLogTranslationKey.Denied]: 'Bạn không có quyền xem nhật ký hoạt động.',
  [AuditLogTranslationKey.ExportError]: 'Không thể xuất CSV lúc này.',
  [AuditLogTranslationKey.ExportTooLarge]:
    'Kết quả quá lớn để xuất. Hãy thu hẹp bộ lọc rồi thử lại.',
  [AuditLogTranslationKey.DetailTitle]: 'Chi tiết hoạt động',
  [AuditLogTranslationKey.DetailClose]: 'Đóng',
  [AuditLogTranslationKey.DetailTechnical]: 'Thông tin kỹ thuật',
  [AuditLogTranslationKey.DetailNoPermission]:
    'Bạn chưa được cấp quyền xem thông tin kỹ thuật.',
  [AuditLogTranslationKey.DetailRequestId]: 'Mã yêu cầu',
  [AuditLogTranslationKey.DetailMethod]: 'Phương thức',
  [AuditLogTranslationKey.DetailPath]: 'Đường dẫn',
  [AuditLogTranslationKey.DetailStatus]: 'Mã trạng thái',
  [AuditLogTranslationKey.DetailSource]: 'Nguồn',
  [AuditLogTranslationKey.DetailTargetId]: 'Mã đối tượng',
  [AuditLogTranslationKey.DetailChangedFields]: 'Trường đã đổi',
  [AuditLogTranslationKey.DetailResult]: 'Kết quả',
  [AuditLogTranslationKey.DetailBefore]: 'Trước thay đổi',
  [AuditLogTranslationKey.DetailAfter]: 'Sau thay đổi',
  [AuditLogTranslationKey.OpenTarget]: 'Mở đối tượng',
};
